config/routes.rb
require 'api_constraints'

Kiddospots::Application.routes.draw do
  resources :events

  resources :android_beta_testers

  resources :event_suggestions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
             :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :places do
        resources :photos 
        match 'photos/upload', to: 'photos#upload', via: :post
        match 'user_reviewed', to: 'reviews#user_reviewed', via: :post
        resources :reviews do
          match 'vote', to: 'reviews#vote', via: :post
        end
      end      

      match 'values/categories', to: 'values#categories', via: :get
      match 'values/features', to: 'values#features', via: :get
      match 'values/age_groups', to: 'values#age_groups', via: :get

      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        patch 'registrations' => 'registrations#update', :as => 'user_update'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
        
    end
  end

  resources :photos
  resources :reviews do
    member { post :vote }
  end

  resources :places do
      member { post :vote }
  end

  resources :places do
    resources :reviews
    resources :photos
  end
  resources :users

 devise_scope :user do 
      match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  apipie
  root  'welcome#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/auth/:provider/callback', to: 'sessions#createfb', via: 'get'

  match '/android_beta', to: 'android_beta_testers#new', via: 'get'
  

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include EventsHelper
  def index
  	@map_coords_hash =[]
  	#Random 6 places within 8 miles. I attempted to use the "random" mysql/sqlite calls, but they
  	#were not actually being random
  	@current_city_places = Place.near(JSON.parse(cookies[:users_latlon]), 50).not_expired.starts_before(Date.today + 7).first(6)
  	
    #If not current location has been set, then we just default to Seattle
  	if @current_city_places.empty?
  		@users_city = "Seattle"
  		@current_city_places = Place.near(@users_city, 8).not_expired.starts_before(Date.today + 7).first(6)
  	end

  	@current_city_places.each do |place|
  		category = Category.find(place.category_id).name
  		@map_coords_hash << {:lat => place.latitude, :lng => place.longitude, 
  			:infowindow => render_to_string(:partial => "welcome/infowindow", :locals => { :place_obj => place }) }
  	end

  	#5 Most recent reviews
  	@latest_reviews = Review.order('created_at DESC').limit(5)
  	#5 Most recently added places
  	@latest_places = Place.order('created_at DESC').limit(5)
  	#7 Upcoming events that take place on today's date
    @upcoming_events = eventsThatDay(Date.today)
  	#4 places that are featured
  	#TODO: Change the large 30 number to something smaller once we get more data. For now, we want to make sure it
  	#always shows 4.
  	@featured_places = Place.near(JSON.parse(cookies[:users_latlon]), 30).not_expired.starts_before(Date.today + 7).where("rating >= 2.5").shuffle[0..5]
  end

  before_filter :set_city
  def set_city
    defaultDistanceMi = 100
  	#If no location is given by user and we have no saved city/latlong saved in the cookies
  	#we default to Seattle
  	if params[:location].blank? && (cookies[:users_city].blank? || cookies[:users_latlon].blank? || cookies[:users_lat].blank? || cookies[:users_lon].blank?)
  		@users_city = "Seattle"
  		cookies.permanent[:users_city] = @users_city
  		coordinates = Geocoder.coordinates(@users_city)
  		cookies.permanent[:users_latlon] = JSON.generate(coordinates)
  		cookies.permanent[:users_lat] = coordinates[0]
  		cookies.permanent[:users_lon] = coordinates[1]
  	end

  	unless params[:location].blank?

  		location = Geocoder.search(params[:location])
  		unless location.blank?
        distance = Geocoder::Calculations.distance_between(location.first.coordinates, [47.606209, -122.332071])
        if distance > defaultDistanceMi
          flash.now[:error] = 'Currently Joeysearch only supports the greater Seattle area, if the given location is within that area, make sure the city is included'
        else
    			@users_city = location.first.city
    			cookies.permanent[:users_city] = @users_city
    			cookies.permanent[:users_latlon] = JSON.generate(location.first.coordinates)
    			cookies.permanent[:users_lat] = location.first.coordinates[0]
    			cookies.permanent[:users_lon] = location.first.coordinates[1]
          flash.now[:success] = 'Location updated successfully'
        end
	  	else
        flash.now[:error] = 'Location not found'
	  		@users_city = cookies[:users_city]
	  	end
	else
		@users_city = cookies[:users_city]
  	end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/welcome/_infowindow.html.erb
<%= link_to place_obj.name, place_obj, style:'font-weight: bold;', 'data-no-turbolink' => true %>

<p><strong><%= Category.find(place_obj.category_id).name %></strong></p>

<%= content_tag "div", id: "review_value", data: {rating: place_obj.rating} do %>  
	<div id="star_value"></div> 
<% end %>

<p>
	<%= place_obj.street %> <br>
	<%= "#{place_obj.city}, #{place_obj.state} - #{place_obj.zip_code}" %>
</p>

<p>
	<% address = "#{place_obj.street} #{place_obj.city}, #{place_obj.state} - #{place_obj.zip_code}" %>
	<%= link_to "Directions", "http://maps.google.com/maps?saddr=&daddr=#{address}", target: '_blank' %>
</p>

app/views/welcome/_infowindow.mobile.erb
<%= link_to place_obj.name, place_obj, style:'font-weight: bold;', "data-ajax" => "false" %>

<p><strong><%= Category.find(place_obj.category_id).name %></strong></p>

app/views/welcome/_locationform.html.erb
<%= button_tag "Change Location", class: "changelocationbutton btn-link"%>
<div class="row-fluid" id="locationform">
	<%= form_tag root_path, method: 'get' do %>
	  <%= text_field_tag :location, params[:location], class: "search-query span3", placeholder: "Enter Location" %>
	  <%= button_tag("Go", type: "submit") %>
	<% end %>
</div>
<script>
	$('#location').val('');
</script>

app/views/welcome/_locationform.mobile.erb
<a href="#" id="getCurrentLocation" data-role="button" data-inline="true" data-icon="star">Current Location</a>
<%= form_tag root_path, method: 'get', 'data-ajax' => 'false', id: "location_form" do %>
  <%= text_field_tag :location, params[:location], placeholder: "Enter Location" %>
  <%= button_tag("Submit", type: "submit", "data-inline" => "true", "data-role" => "button") %>
<% end %>

<script>
  jQuery(function() {
    $('#location').val('');
    
    $( document ).on( "click", "#getCurrentLocation", function() {
      currentLocation();
    });

    function successFunction(position) {
        var lat = position.coords.latitude;
        var lon = position.coords.longitude;
        $('#location').val(lat + ', ' + lon);
        $( "#location_form" ).submit();
    }

    function errorFunction(error) {
          switch (error.code) {
          case error.PERMISSION_DENIED:
              alert("Joeysearch was not allowed to use your current location");
              break;

          case error.POSITION_UNAVAILABLE:
              alert("Joeysearch could not find your current location");
              break;

          case error.TIMEOUT:
              alert("Joeysearch timed out retrieving your current location");
              break;

          case error.UNKNOWN_ERROR:
              alert("Joeysearch encountered an unknown error while retrieving your current location");
              break;
          }
          return;
      }

      function currentLocation() {
        if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(successFunction, errorFunction)
      }
      }
  });
</script>

app/views/welcome/index.html.erb
<head> 
  <%= analytics_init if Rails.env.production? %> 
</head>
<% meta og: 
  { 
    title: "Joeysearch", description: "Joeysearch is your local guide to all things kid-friendly!", url: "http://www.joeysearch.com/", image: 'http://www.joeysearch.com/assets/joeysearch_facebook.png'
  } 
%>
<% unless user_signed_in? %>
  <div class="well bg-d widget" id="headerbox">
    <div class="row-fluid">
      <div class="span9">
        <h3><font color=#005580>Joeysearch is your local guide to all things kid-friendly!</font></h3>
      </div>
      <div class="span3" id="headerlogobox">
        <%= image_tag("joeybanner.png", alt: "Joey Search") %>
      </div>
    </div>
    <div class="span6" id="headerboxbuttonbox">
      <%= link_to 'Create your free account', new_user_registration_path, :class => "btn btn-info" %>
    </div>
  </div>
<% end %>
<div class="row-fluid">
  <div class="span12">
    <h4><font color=#005580> Joeysearch: <%= @users_city %> </font></h4>
    <%= render "locationform" %>
  </div>
</div>
<br>
<%= form_tag places_path, method: 'get' do %>
  Search By Category:
  <%= collection_select :category_id, params[:category_id], Category.order(:name), :id, :name, :include_blank => "Select Category", class: "category_search" %>
  <%= button_tag("Go", type: "submit", "id" => "category_search_button", class: "btn btn-info") do %>
    <i class="micon-search"></i>
  <% end %>
<% end %>
<div class="row-fluid">
  <div class="span6">    
    <table class="table">
      <tbody>
        <% @current_city_places.each_with_index do |place, index| %>
          <tr>
            <td>
              <div class="result_div">
                <% if place.photos[0] %>
                  <%= link_to(image_tag(place.photos[0].image_url(:thumb).to_s, size: "100x100"), place)  %>
                <% else %>
                  <%# Adding 1 since index starts with 0 %>
                  <!--[if lte IE 9]>
                    <%= image_tag('thumbnail-default-100.jpg', alt: "Default Image") %>
                  <![endif]-->
                  <![if (gt IE 9) | !(IE)]>
                     <%= image_tag('thumbnail-default.jpg', alt: "Default Image", :class => "result_default") %>
                  <![endif]>
                <% end %>
              </div>
            </td>
            <td><%= index+1 %><%= ". " %><%= link_to place.name, place, 'data-no-turbolink' => true %>
              <br><%= Category.find(place.category_id).name %> 
            </td>
            <td>
              <%= content_tag "div", id: "review_value", data: {rating: place.rating} do %>  
                <div id="star_value"></div> 
              <% end %>
              <font size='1'>Kid-Friendly Rating</font><br>
              <small><%= pluralize(place.reviews.count, 'Review') %></small><br>
              <% if place.votes > 0 %>
                <small><%= pluralize(place.votes, 'Like!')%></small>
              <% end %>
            </td>
          </tr> 
        <% end %>
      </tbody>
    </table>
          <%= link_to "More Nearby Joey Spots . . .", places_path(:name => "", :near => "") %>
  </div>
	<div class="span6" id="home_map">
    <%= content_tag "div", class: 'google-maps', id: "map", style: 'width: 100%; height: 600px;', data: { coords: @map_coords_hash.to_json} do %>
    <% end %>
  </div>
</div>

<br><br><br>

<div class="well widget">
  <!-- widget header -->
  <div class="widget-header">
    <h3 class="title">Featured Joey Spots</h3>
  </div>
  <!-- ./ widget header -->
  <br>
  <div class="row-fluid">
    <div class="span3" align="center">
      <% if @featured_places[0]%>
        <div class="cube">
          <% if @featured_places[0].photos[0] %>
            <%= link_to(image_tag(@featured_places[0].photos[0].image_url(:thumb).to_s, size: "100x100"), @featured_places[0]) %>
          <% else %>
              <!--[if lte IE 9]>
                <%= image_tag('thumbnail-default-100.jpg', alt: "Default Image") %>
              <![endif]-->
              <![if (gt IE 9) | !(IE)]>
                 <%= image_tag('thumbnail-default.jpg', alt: "Default Image", :class => "result_default") %>
              <![endif]>
          <% end %>
        </div>
        <br>
        <%= link_to @featured_places[0].name, @featured_places[0], 'data-no-turbolink' => true %><br>
        <%= content_tag "div", id: "review_value", data: {rating: @featured_places[0].rating} do %>  
            <div id="star_value"></div> 
        <% end %>
      <% end %>
    </div>
    <div class="span3" align="center">
      <% if @featured_places[1] %>
        <div class="cube">
          <% if @featured_places[1].photos[0] %>
            <%= link_to(image_tag(@featured_places[1].photos[0].image_url(:thumb).to_s, size: "100x100"), @featured_places[1]) %>
          <% else %>
              <!--[if lte IE 9]>
                <%= image_tag('thumbnail-default-100.jpg', alt: "Default Image") %>
              <![endif]-->
              <![if (gt IE 9) | !(IE)]>
                 <%= image_tag('thumbnail-default.jpg', alt: "Default Image", :class => "result_default") %>
              <![endif]>
          <% end %>
        </div>
        <br>
        <%= link_to @featured_places[1].name, @featured_places[1], 'data-no-turbolink' => true %><br>
        <%= content_tag "div", id: "review_value", data: {rating: @featured_places[1].rating} do %>  
            <div id="star_value"></div> 
        <% end %>
      <% end %>
    </div>
    <div class="span3" align="center">
      <% if @featured_places[2] %>
        <div class="cube">
          <% if @featured_places[2].photos[0] %>
            <%= link_to(image_tag(@featured_places[2].photos[0].image_url(:thumb).to_s, size: "100x100"), @featured_places[2]) %>
          <% else %>
              <!--[if lte IE 9]>
                <%= image_tag('thumbnail-default-100.jpg', alt: "Default Image") %>
              <![endif]-->
              <![if (gt IE 9) | !(IE)]>
                 <%= image_tag('thumbnail-default.jpg', alt: "Default Image", :class => "result_default") %>
              <![endif]>
          <% end %>
        </div>
        <br>
        <%= link_to @featured_places[2].name, @featured_places[2], 'data-no-turbolink' => true %><br>
        <%= content_tag "div", id: "review_value", data: {rating: @featured_places[2].rating} do %>  
            <div id="star_value"></div> 
        <% end %>
      <% end %>
    </div>
    <div class="span3" align="center">
      <% if @featured_places[3] %>
        <div class="cube">
          <% if @featured_places[3].photos[0] %>
            <%= link_to(image_tag(@featured_places[3].photos[0].image_url(:thumb).to_s, size: "100x100"), @featured_places[3]) %>
          <% else %>
              <!--[if lte IE 9]>
                <%= image_tag('thumbnail-default-100.jpg', alt: "Default Image") %>
              <![endif]-->
              <![if (gt IE 9) | !(IE)]>
                 <%= image_tag('thumbnail-default.jpg', alt: "Default Image", :class => "result_default") %>
              <![endif]>
          <% end %>
        </div>
        <br>
        <%= link_to @featured_places[3].name, @featured_places[3], 'data-no-turbolink' => true %><br>
        <%= content_tag "div", id: "review_value", data: {rating: @featured_places[3].rating} do %>  
            <div id="star_value"></div> 
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
</div>

<br><br><br>

<div class="row-fluid">
  <div class="span4">
    <div class="well widget">
      <!-- widget header -->
      <div class="widget-header">
        <h3 class="title">Today's Events</h3>
      </div>
        <% if @upcoming_events.blank? %>
          There are no events in your area.
          <br><br>
        <% else %>
          <% @upcoming_events.first(7).each do |event| %>
            <div class="row-fluid">
              <div class="span2" id="event_line">
                <% unless event.image.blank? %>
                  <%= image_tag(event.image_url.to_s, id: "event_image") %>
                <% else %>
                  <%# Adding 1 since index starts with 0 %>
                  <%= image_tag('thumbnail-default.jpg', alt: "Default Image") %>
                <% end %>
              </div>
              <div class="span6" id="event_line">
                <%= link_to event.name, event, 'data-no-turbolink' => true %>
              </div>
              <div class="span4" id="event_line" align="right">
                <%= event.city %>
              </div>
            </div>
            <br>
          <% end %>
        <% end %>
        <%= link_to "Full Events Calendar . . .", events_path %>
    </div>
  </div>
  <div class="span4">
    <div class="well widget">
      <div class="widget-header">
        <h3 class="title">Latest Reviews</h3>
      </div>
      <% @latest_reviews.each do |review| %>
        <div class="row-fluid">
        <div class="span2">
          <% if !review.user.image.blank? %>
            <%= link_to(image_tag(review.user.image_url(:thumb).to_s, size:"80x80"), review.user) %>
          <% else %>
            <%= image_tag('profile-default.png', size: "80x80", alt: "Default Image") %>
          <% end %>
        </div>
        <div class="span10">
          <%= link_to name_format(User.find(review.user_id).name), user_path(User.find(review.user_id).slug) %>
          reviewed 
          <%= link_to review.place.name, review.place, 'data-no-turbolink' => true %>
          <%= time_ago_in_words(review.created_at) %> ago
          <%= content_tag "div", id: "review_value", data: {rating: review.place.rating} do %>  
            <div id="star_value"></div> 
          <% end %>
        </div>
      </div>
        <br>
      <% end %>
    </div>
  </div>

 

  <div class="span4">
    <div class="well widget">
      <div class="widget-header">
        <h3 class="title">Recently Added Joey Spots</h3>
      </div>
    	<% @latest_places.each do |place| %>
        <div class="row-fluid">
          <div class="span3">
            <% if place.photos[0] %>
              <%= link_to(image_tag(place.photos[0].image_url(:thumb).to_s), place, size:"50x50")  %>
            <% else %>
              <%# Adding 1 since index starts with 0 %>
              <%= image_tag('thumbnail-default.jpg', size: "80x80", alt: "Default Image") %>
            <% end %>
          </div>
          <div class="span8">
        		<%= link_to place.name, place, 'data-no-turbolink' => true %><br>
            <small><%= Category.find(place.category_id).name %></small>
      	    <%= content_tag "div", id: "review_value", data: {rating: place.rating} do %>  
            <div id="star_value"></div> 
          </div>
        </div>
  	    <% end %>
    		<br>
    	<% end %>
    </div>
  </div>

</div>

app/views/welcome/index.mobile.erb
<% meta og: 
  { 
    title: "Joeysearch", description: "Joeysearch is your local guide to all things kid-friendly!", url: "http://www.joeysearch.com/", image: 'http://www.joeysearch.com/assets/joeysearch_facebook.png'
  } 
%>

<div id="home" data-role="page">
  <%= render 'layouts/header' %>
  <div data-role="content">
    <%= render 'layouts/flash_message' %>
    <div data-role="collapsible" data-collapsed-icon="carat-d">
        <h4><font color=#005580> Joeysearch: <%= @users_city %></h4>
        <p><%= render "locationform" %></p>
    </div>
    <br>
    
    <ul data-role="listview" data-inset="false">
      <li data-role="list-divider">
        Nearby Joey Spots
      </li>
      <% if @current_city_places.empty? %>
        There are no nearby places for your location
      <% end %>
      <% @current_city_places.each_with_index do |place, index| %>
        <li>
          <%= link_to place, "data-ajax" => "false" do %>
            <% if place.photos[0] %>
              <%= image_tag(place.photos[0].image_url(:thumb).to_s, size: "70x70")  %>
            <% else %>
              <%# Adding 1 since index starts with 0 %>
              <%= image_tag('thumbnail-default.jpg', size: "70x70", alt: "Default Image") %>
            <% end %>
            <%= index+1 %>
              <%= ". " %><%= place.name %>
              <div id="mobile_home_review_value" >
                <%= content_tag "div", id: "review_value", data: {rating: place.rating} do %>
                  <div id="star_value"></div> 
                <% end %>
              </div>
              <font size='1'>Kid-Friendly Rating</font>
              <font size='1'>(<%= pluralize(place.reviews.count, 'Review') %>)</font><br>
              <% if place.votes > 0 %>
                <small><%= image_tag('heart.png', id: 'like_result', size: '15x15') %>&nbsp <%= place.votes %></small><br>
              <% end %>
              <small><font size='2' color = "gray"> <%= Category.find(place.category_id).name %> </font></small>
          <% end %>
        </li>
      <% end %>
      <li>
        <%= link_to "More . . .", places_path(:name => "", :near => ""), 'data-ajax' => 'false' %>
      </li>
      <li>
        <center>
            <%= content_tag "div", class: 'google-maps', id: "map", style: 'width: 90%; height: 300px; max-width: 400px', data: { coords: @map_coords_hash.to_json} do %>
          <% end %>
        </center>
      </li>
    </ul>
    <br>
    <br>
    <ul data-role="listview">
      <li data-role="list-divider">
        Search By Category
      </li>
      <li>
        <%= link_to "Parks,Playgrounds,Beaches,Hikes", places_path(:category_id => 1), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Restaurants and Cafes", places_path(:category_id => 3), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Museums,Aquariums,Zoos,Farms", places_path(:category_id => 2), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Pools, Recreation/Community Centers", places_path(:category_id => 4), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Indoor Activity Center", places_path(:category_id => 15), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Theaters", places_path(:category_id => 5), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Schools and Day Cares", places_path(:category_id => 9), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Retail/Grocery Stores, Malls", places_path(:category_id => 8), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Dentists, Physicians and Health", places_path(:category_id => 10), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Amusement Parks", places_path(:category_id => 11), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Hotel and Accommodations", places_path(:category_id => 12), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Libraries and Book Stores", places_path(:category_id => 17), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Attractions", places_path(:category_id => 13), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Salons and Barber Shops", places_path(:category_id => 16), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Classes,Lessons,Leagues,Camps", places_path(:category_id => 6), 'data-ajax' => 'false' %>
      </li>
      <li>
        <%= link_to "Events", events_path, 'data-ajax' => 'false' %>
      </li>
    </ul>
    <br>
  </div>
  <br>
  <center>
    <%= link_to "Full Site", root_path(:mobile => 0), "data-ajax" => "false", :class => "ui-btn ui-btn-inline" %>
  </center>

  <%= javascript_include_tag "mobile/mobile" %>
  <%= javascript_include_tag "mobile/maps_results.mobile" %>
  <%= javascript_include_tag "mobile/places.mobile" %>

</div>