config/routes.rb
require 'api_constraints'

Kiddospots::Application.routes.draw do
  resources :events

  resources :android_beta_testers

  resources :event_suggestions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
             :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :places do
        resources :photos 
        match 'photos/upload', to: 'photos#upload', via: :post
        match 'user_reviewed', to: 'reviews#user_reviewed', via: :post
        resources :reviews do
          match 'vote', to: 'reviews#vote', via: :post
        end
      end      

      match 'values/categories', to: 'values#categories', via: :get
      match 'values/features', to: 'values#features', via: :get
      match 'values/age_groups', to: 'values#age_groups', via: :get

      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        patch 'registrations' => 'registrations#update', :as => 'user_update'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
        
    end
  end

  resources :photos
  resources :reviews do
    member { post :vote }
  end

  resources :places do
      member { post :vote }
  end

  resources :places do
    resources :reviews
    resources :photos
  end
  resources :users

 devise_scope :user do 
      match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  apipie
  root  'welcome#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/auth/:provider/callback', to: 'sessions#createfb', via: 'get'

  match '/android_beta', to: 'android_beta_testers#new', via: 'get'
  

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	validates :image, :presence => true
	belongs_to :place
	belongs_to :review

	mount_uploader :image, ImageUploader
	# validates_presence_of :image

	def default_description
	  self.description ||= File.basename(image.filename, '.*').titleize if image
	end

	def next
		place.photos.where("id > ?", id).order("id ASC").first
	end

	def prev
		place.photos.where("id < ?", id).order("id DESC").first
	end
	
end

app/controllers/api/v1/photos_controller.rb
module Api
	module V1
		class PhotosController < ApplicationController

			def index
				if params[:place_id]
					place = Place.find(params[:place_id])
					@photos = place.photos
				end
			end


			api :POST, '/places/:place_id/photos/upload', "Upload a photo"
			param :email, String , :desc => "Login email", :required => true
			param :auth_token, String , :desc => "Auth token generated on login", :required => true
			param :photo, Hash , :desc => "Photo object", :required => true do
				param :description, String , :desc => "Description of the image", :required => false
				param :review_id, Integer, :desc => "ID of the review to which the photo belongs", :required => false
				param :image, Hash, :desc=>"Image object", :required=>true do
					param :content_type, String, :desc => "Image type. For examople: image/jpeg", :required => true
					param :filename, String, :desc => "Image's file name", :required => true
					param :original_filename, String, :desc => "Same as image's file name", :required => true
					param :file_data, String, :desc => "Base64 encoded image", :required => true
				end
			end
			description <<-EOS

			Example Request JSON:

			<tt>
			{ "auth_token" : "GRfYzH2Ki1y99U5znQPj", "email" : "user@gmail.com", "photo" : { "description" : "a description of the image", "review_id" : 1, "image" : {"content_type" : "image/jpeg", "filename" : "image001.JPG", "original_filename" : "image001.JPG", "file_data" : base64_encoded_string} } }
			</tt>

			Example JSON response:

			<tt>
				{"success":true,"photo_id":9,"photo":{"image":{"url":"https://kiddospots-dev.s3.amazonaws.com/uploads/photo/image/9/image.JPG","thumb":{"url":"https://kiddospots-dev.s3.amazonaws.com/uploads/photo/image/9/thumb_image.JPG"}}}}
			</tt>
			EOS


			def upload
				user = User.where(:authentication_token => params[:auth_token])

				place = Place.find(params[:place_id])

				# @photo.image.set_filename(params[:photo][:image])
				
				photo_params[:image] = parse_image_data(photo_params[:image]) if photo_params[:image]

				@photo = place.photos.build(photo_params)
				@photo.user_id = user.first.id
				
				if @photo.save
					@photo
				else
					render json: { success: false, error: @photo.errors }
				end

			ensure
				clean_tempfile
			end

			def photo_params 
				@photo_params ||= params.require(:photo).permit(:description, :review_id, image:[:content_type, :filename, :file_data])
			end

			private

			def parse_image_data(image_data)
				@tempfile = Tempfile.new('uploaded-photo')
				@tempfile.binmode
				@tempfile.write Base64.decode64(image_data[:file_data])
				@tempfile.rewind

				ActionDispatch::Http::UploadedFile.new(
					:tempfile => @tempfile,
					:content_type => image_data[:content_type],
					:filename => image_data[:filename],
					:original_filename => image_data[:original_filename]
				)
			end

			def clean_tempfile
				if @tempfile
					@tempfile.close
					@tempfile.unlink
				end
			end


		end
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :update, :new, :edit]

  # GET /photos
  # GET /photos.json
  def index
    place = Place.find(params[:place_id])
    if mobile_device?
      @photos = place.photos.paginate(page: params[:page], per_page: 9)
    else
      @photos = place.photos
    end

    @photo = place.photos.build
    respond_to do |format|
      format.html # index.html.erb
    end

  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @place = Place.find(params[:place_id])
    @photo = @place.photos.find(params[:id])
    @first_photo = Photo.where(place_id: @photo.place_id).first
    @last_photo = Photo.where(place_id: @photo.place_id).order("id DESC").first # Read that .last is slow when there are lots of records 
    respond_to do |format|
      format.html # index.html.erb
    end      
  end

  # GET /photos/new
  def new
    place = Place.find(params[:place_id])
    @photo = place.photos.build
    respond_to do |format|
      format.html # index.html.erb
    end      
  end

  # GET /photos/1/edit
  def edit
    place = Place.find(params[:place_id])    
    @photo = place.photos.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    place = Place.find(params[:place_id])
    if params[:photo]
      respond_to do |format|
        @photo = place.photos.build(params[:photo].permit(:description, :image))
        @photo.user_id = current_user.id
        debugger
        if @photo.save
          format.html { redirect_to [@photo.place, @photo], notice: 'Photo was successfully created.' }
          format.json { render action: 'show', status: :created, location: @photo }
          format.js
          format.mobile { redirect_to place_photos_path(place), flash: { success: 'Photo was successfully created.' } }
        else
          format.html { render action: 'new' }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
          format.js
          format.mobile { redirect_to place_photos_path(place), flash: { error: 'Error saving photo' } }
        end
      end
    else
      redirect_to place_photos_path(place), flash: { error: 'Error saving photo' }
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    place = Place.find(params[:place_id])
    @photo = place.photos.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo].permit(:image, :description))
        format.html { redirect_to [@photo.place, @photo], flash: { success:'Photo was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    place = Place.find(params[:place_id])
    @photo = place.photos.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to place_photos_url  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def photo_params
    #   params.require(:photo).permit(:place_id, :description, :image, :user_id)
    # end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for([@photo.place, @photo]) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= image_tag @photo.image_url %>

  <div class="field">
    <br><strong>Description:</strong>
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/photos/_form.mobile.erb
<%= render 'shared/error_messages', :target => @photo %>
<%= form_for([@photo.place, @photo], :html => { :'data-ajax' => false }) do |f| %>
  <br>
  <%= f.label :image, "Upload a photo:" %>
  <%= f.file_field :image, name: "photo[image]" %>
  
  <%= f.submit "Upload Photo", class: "btn btn-default btn-primary" %>
<% end %>

app/views/photos/_photo.html.erb
<div class="photo">
  <%= link_to(image_tag(photo.image_url(:thumb).to_s), ([photo.place, photo] if photo.image?))  %>
</div>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert("Failed to upload photo: <%= j @photo.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#photos").append("<%= j render(@photo) %>");
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', [@photo.place, @photo] %> |
<%= link_to 'Back', place_photos_path(@photo.place) %>

app/views/photos/index.html.erb
<h3>Photos for <%= link_to @photo.place.name, place_path(@photo.place) %></h3>

<div id="photos">
	<% if @photos.count == 0 %>
		No photos have been added for this Joey Spot.
		<br><br>
	<% end %>
	<% @photos.each do |item| %>
		<% if item.id %>
		    <%= render 'photo', :photo => item %>
	    <% end %>
	<% end %>
</div>
<div class="clear"></div>

<% if current_user %>
 	<%= form_for [@photo.place, @photo] do |f| %>  
		<strong>Upload Photos</strong><br><br>
	  	Choose files or drag and drop files to this window<br><br>
	  	<%= f.file_field :image, multiple: true, name: "photo[image]" %>
	<% end %>

	<script id="template-upload" type="text/x-tmpl">
	<div class="">
	  {%=o.name%}
	  <div class="progress progress-striped"><div class="bar" style="width: 0%"></div></div>
	</div>
	</script>
	
<% else %>
	<br><br><br><br><br><br>
<% end %>

app/views/photos/index.mobile.erb
<div id = "indexPhotos" data-role="page">
	<%= render 'layouts/header' %>
	<div data-role="content">
			<%= render 'layouts/flash_message' %>
			<div class="ui-grid-b">
				<% if @photos.length <= 0 %>
					No photos to display
				<% end %>
				<% $i = 1 %>
				<% @photos.each do |item| %>
					<% if ($i % 3) == 1 %>
						<% if item.id %>
						    <div class="ui-block-a">
						    	<%= link_to(image_tag(item.image_url(:thumb).to_s), "#photo_"+item.id.to_s, "data-rel" => "popup", "data-position-to" => "window")  %>
						    	<%= div_for item, :class => "photopopup", "data-overlay-theme" => "a", "data-corners" => "false", "data-tolerance" =>"30,15", "data-role" => "popup" do %>
								   <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a><%= image_tag(item.image_url) %>
								<% end %>
						    </div>
					    <% end %>
				    <% end %>
				    <% if ($i % 3) == 2 %>
					    <% if item.id %>
						    <div class="ui-block-b">
						    	<%= link_to(image_tag(item.image_url(:thumb).to_s), "#photo_"+item.id.to_s, "data-rel" => "popup", "data-position-to" => "window")  %>
						    	<%= div_for item, :class => "photopopup", "data-overlay-theme" => "a", "data-corners" => "false", "data-tolerance" =>"30,15", "data-role" => "popup" do %>
								   <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a><%= image_tag(item.image_url) %>
								<% end %>
						    </div>
					    <% end %>
				    <% end %>
				    <% if ($i % 3) == 0 %>
					    <% if item.id %>
						    <div class="ui-block-c">
						    	<%= link_to(image_tag(item.image_url(:thumb).to_s), "#photo_"+item.id.to_s, "data-rel" => "popup", "data-position-to" => "window")  %>
						    	<%= div_for item, :class => "photopopup", "data-overlay-theme" => "a", "data-corners" => "false", "data-tolerance" =>"30,15", "data-role" => "popup" do %>
								   <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a><%= image_tag(item.image_url) %>
								<% end %>
						    </div>
					    <% end %>
				    <% end %>
				    <% $i = $i + 1 %>
				<% end %>
			</div>
			<%= will_paginate @photos, 
			    renderer: WillPaginate::ActionView::JqueryMobilePaginateLinkRenderer,
			    previous_label: 'Prev',
			    next_label: 'Next'
			  %>
			<% if current_user %>
			 	<%= render 'form' %>
			<% end %>
			<br>
			<center>
				<%= link_to "Full Site", root_path(:mobile => 0), "data-ajax" => "false", :class => "ui-btn ui-btn-inline" %>
			</center>
	</div>
	<%= javascript_include_tag "jquery_ujs" %>
	<script>
		$( document ).on( "pagecreate", function() {
		    $( ".photopopup" ).on({
		        popupbeforeposition: function() {
		            var maxHeight = $( window ).height() - 60 + "px";
		            $( ".photopopup img" ).css( "max-height", maxHeight );
		        }
	    	});
		});
	</script>
	<style>
		.ui-grid-b img {
		    width  : 100%;
		    height : auto;
		}
	</style>
</div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<p>
  <strong>
  	<%= link_to "Back", place_path(@photo.place) %> to photos of <%= link_to @photo.place.name, place_path(@photo.place) %>
  </strong>
</p>

<% isFirst = @first_photo == @photo %>
<% isLast = @last_photo == @photo %>
<% unless isFirst %>
<%= link_to "Previous", place_photo_path(@place, @photo.prev) %> 
<% end %>  
<% unless isFirst || isLast %>
|
<% end %>
<% unless isLast %>
<%= link_to "Next", place_photo_path(@place, @photo.next) %>
<% end %>

<p>
  <%= image_tag @photo.image_url %>
</p>

<p>
  <%= @photo.description %>
</p>

<p>
  <strong>Uploaded by:</strong>
  <%= link_to name_format(User.find(@photo.user_id).name), user_path(User.find(@photo.user_id).slug) %>
</p>

<%= link_to 'Back', place_path(@photo.place) %> 

<% if (current_user && (@photo.user_id == current_user.id)) || (current_user && current_user.id == 2) %>
	|
	<%= link_to 'Edit Description', edit_place_photo_path(@photo.place, @photo) %> |
	<%= link_to "Delete", [@photo.place, @photo], :data => {:confirm => 'Are you sure you want to delete this photo ?'}, :method => :delete %>
<% end %>