config/routes.rb
require 'api_constraints'

Kiddospots::Application.routes.draw do
  resources :events

  resources :android_beta_testers

  resources :event_suggestions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
             :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :places do
        resources :photos 
        match 'photos/upload', to: 'photos#upload', via: :post
        match 'user_reviewed', to: 'reviews#user_reviewed', via: :post
        resources :reviews do
          match 'vote', to: 'reviews#vote', via: :post
        end
      end      

      match 'values/categories', to: 'values#categories', via: :get
      match 'values/features', to: 'values#features', via: :get
      match 'values/age_groups', to: 'values#age_groups', via: :get

      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        patch 'registrations' => 'registrations#update', :as => 'user_update'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
        
    end
  end

  resources :photos
  resources :reviews do
    member { post :vote }
  end

  resources :places do
      member { post :vote }
  end

  resources :places do
    resources :reviews
    resources :photos
  end
  resources :users

 devise_scope :user do 
      match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  apipie
  root  'welcome#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/auth/:provider/callback', to: 'sessions#createfb', via: 'get'

  match '/android_beta', to: 'android_beta_testers#new', via: 'get'
  

  

end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :category
	has_many :reviews, dependent: :destroy
	belongs_to :user
	has_many :places_age_groups, dependent: :destroy
	has_many :age_groups, through: :places_age_groups
	has_many :places_features, dependent: :destroy
	has_many :features, through: :places_features
	has_many :business_hours, dependent: :destroy
	accepts_nested_attributes_for :business_hours, allow_destroy: true
	has_many :photos, dependent: :destroy
	has_many :place_votes, dependent: :destroy

	validates :name, presence: true 
	validates :category_id, presence: true 
	validates :street, presence: true 
	validates :city, presence: true 
	validates :state, presence: true 
	validates_numericality_of :zip_code
	validates :website, url: true
	validates :user_id, presence: true
	validates :business_hours, days: true
	validates :event_price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than_or_equal_to => 0.00}, allow_blank: true
	validates_presence_of :event_start_date, :unless => :not_event_type?
	validates_presence_of :recurrence_id, :unless => :not_event_type?
	validates_presence_of :event_end_date, :if => :happens_once?, :message => "must be present if the event only occurs once"
	validate :end_date_is_possible?
	validate :place_not_already_present?, :on => :create
	before_save :add_time_to_hours

	# Custom error message in form validation
	validate do |age_group|
		age_group.errors[:base] << "An Age Group must be selected" if age_group.age_group_ids.blank?
	end

	geocoded_by :address
	before_validation :geocode, :if => :address_changed?

	# Query to eliminate expired events
	scope :not_expired, -> {
		where("event_end_date >= ? OR event_end_date IS NULL", Date.today)
	}

	# Query to check if the start date is before a certain dat
	scope :starts_before, ->(day) { 
		where("event_start_date <= ? OR event_start_date IS NULL", day)
	}

	searchable do
		text :name, :boost => 5
		text :description
		text :category do
			category.name if category
		end
		text :features do |place|
			place.features.map{|feature| feature.name}
		end
		text :reviews do
			reviews.map(&:review)
		end
		# location :location
		latlon(:location) { Sunspot::Util::Coordinates.new(latitude, longitude)}
		time :event_end_date
	end

	# Helper for custom validation for website. Adds http:// if not present
	def website= url_str
	  unless url_str.blank?
		unless url_str.split(':')[0] == 'http' || url_str.split(':')[0] == 'https'
			url_str = "http://" + url_str
		end
	  end
	  write_attribute :website, url_str
	end

	# Strip non-digit characters from phone number
	def phone_num= phone_str
		phone_str.to_s.gsub!(/\D/, '')
		write_attribute :phone_num, phone_str
	end

	# Performs search on name & city
	def self.search_simple near, name
		return scoped unless near.present? || name.present?
		if name != "" && near != ""
			return where(['name LIKE ?', "%#{name}%"]) & Place.near("%#{near}%",40) 
		elsif near == ""
			return where(['name LIKE ?', "%#{name}%"])  
		elsif name == ""
			Place.near("%#{near}%",40) 
		end
	end	

	extend FriendlyId
	friendly_id :slug_candidates, use: [:slugged, :finders]

	def self.by_votes
	 	select('places.*, coalesce(value, 0) as votes').
	 	joins('left join place_votes on place_id=places.id').
	 	order('votes desc')
	end

	def votes
	 	read_attribute(:votes) || place_votes.sum(:value)
	end

	private
		def end_date_is_possible?
			return if event_end_date.blank?
			if event_end_date < Date.today
				errors.add(:event_end_date, 'is already past todays date')
			end
			return if [event_start_date.blank?, event_end_date.blank?].any?
		    if event_end_date < event_start_date
		    	errors.add(:event_end_date, 'is earlier than start date!')
			end
		end

		def place_not_already_present?
			@similar = Place.where(name: name)
			if @similar.count == 0
				return
			else
				@similar.each do |place|
					if Rails.env.production?
						if place.longitude == longitude.round(6) && place.latitude == latitude.round(6)
							errors.add(:name, 'already exists at this location!')
						end
					else
						if place.longitude == longitude && place.latitude == latitude
							errors.add(:name, 'already exists at this location!')
						end
					end
				end
			end
		end

		def not_event_type?
			category_id != 7
		end

		def happens_once?
			recurrence_id == 1
		end

		# Helpers for address Geocoding
		def address
		  [street, city, state, zip_code].compact.join(', ')
		end

		def address_changed?
			:street_changed? || :city_changed? || :state_changed? || :zipcode_changed? 
		end

		# Try building a slug based on the following fields in
		# increasing order of specificity.
		def slug_candidates
		  [
			:name,
			[:name, :city],
			[:name, :zip_code, :city]
		  ]
		end

		@@timezone = Timezone::Zone.new :zone => 'America/Los_Angeles'

		def add_time_to_hours

			is_dst_on = @@timezone.dst?(Time.now)
			if is_dst_on
				@time_to_add = 1.hour
			else
				@time_to_add = 0
			end

   			unless self.business_hours.blank?
   				self.business_hours.each do |k|
					k.open_time = k.open_time + @time_to_add
   					k.close_time = k.close_time + @time_to_add
   				end
   			end

		end
end

app/helpers/places_helper.rb
module PlacesHelper
	def us_states
	    [
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ]
  	end

  	def daysOfTheWeek
  		# [["Sunday", 0], ["Monday", 1], ["Tuesday", 2], ["Wednesday", 3], ["Thursday", 4], ["Friday", 5], ["Saturday", 6]]
  		["Weekdays", "Weekends", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] 
  	end

  	def intToDay(n)
  		Date::DAYNAMES[n]
  	end

  	def priceDollars
  		[['Free', 0],['$', 1],['$$', 2],['$$$', 3],['$$$$', 4]]
  	end

  	def intToPrice(n)
  		prices = {0=>"Free", 1=>"$", 2=>"$$", 3=>"$$$", 4=>"$$$$"}
  		prices[n]
  	end

  	# Returns an array of age_group_ids. Used in create/edit form to populate checkbox values
	def getAgeGroupIDs(place_id)
	  age_group_id_array = []
	  PlacesAgeGroup.where(place_id: place_id).each do | places_age_group |
	    age_group_id_array << places_age_group.age_group_id
	  end
	  age_group_id_array
	end

	# Returns an array of age_group_ids. Used in create/edit form to populate checkbox values
	def getFeatureIDs(place_id)
	  feature_id_array = []
	  PlacesFeature.where(place_id: place_id).each do | places_feature |
	    feature_id_array << places_feature.feature_id
	  end
	  feature_id_array
	end

end

app/views/places/_form.html.erb
<div class="well widget">
	<!-- widget header -->
	<div class="widget-header">
		<h3 class="title">Joeyspot Information</h3>
	</div>
	<div class="control-group" id="autopopulate_search">
		<%= label_tag :search, "Search to automatically populate location information" %>
		<%= text_field_tag :location_search, nil, class: "span6", type: "search", :placeholder => "Enter a place name or location" %>
		<div id="googlemap"></div>
		<%= render partial: "googlemap" %>
	</div>
	
	<%= form_for(@place) do |f| %>
	  <%= render 'shared/error_messages', :target => @place %>
	  	<div>
	    	<%= f.label :name, "Joey Spot Name" %>
	    	<%= f.text_field :name, :placeholder => "e.g. Woodland Park Zoo", class: "input-xlarge" %>
	    	
	    </div>
	    <div>
	    	<%= f.label :category_id %>
	    	<% # Get all entries from Category table and list them in a drop-down %>       
	   		<%= f.collection_select :category_id, Category.order(:name), :id, :name, :include_blank => "Select Category", class: "cselect" %>
	   	</div>
	   	<div>

	    	<%= f.label :feature_id, "Kid-Friendly Features " %> 
	    	<%= "(Ctrl+Click to select multiple features. ⌘+Click on a Mac)" %>
		    <br>
		    <%= f.grouped_collection_select :feature_ids, Category.order(:name), :features, :name, :id, :name, {:id => "place[feature_ids][]"},  
		    	{:multiple => true, :size => 8} %>
		</div>
		<div>
			<%= f.label "Description (optional)" %>
	    	<%= f.text_area :description,  class: "input-xxlarge", rows: "5"%>
	    </div>

	    <div class="row-fluid">
		    <div class="span4">
		    	<%= f.label "Ages (In Years)" %>
				<%# Check to see if a checkbox box was selected when form validation failed %>
				<% if (params[:place] != nil) && (params[:place][:age_group_ids] !=nil) %>
					<% age_group_id_array = params[:place][:age_group_ids].map(&:to_i) %>
				<% else %>
					<% age_group_id_array = getAgeGroupIDs(@place.id) # To pre-populate the check boxes data selected on page edit %>
				<% end %>

			    <% for age_group in AgeGroup.all %>
					<%= check_box_tag "place[age_group_ids][]", age_group.id, age_group_id_array.include?(age_group.id), type: "checkbox" %>
					<%= f.label age_group.group_name+" ("+age_group.description+")", :class => "checkbox inline" %>
					<br>
			    <% end %>
			 </div>

			 <div class="span3">   
			    <%= f.label :Price %>
		    	<%= f.select :price, priceDollars %>
		    	
		    </div>
		</div>
	    <br>

	    <div class="row-fluid">
		   	<div class="span3">
		   		<%= f.label "Start Date:" %>
		   		<%= f.text_field :event_start_date %>
		   	</div>
		   	<div class="span3">
		   		<%= f.label "End Date (If Applicable):" %>
		   		<%= f.text_field :event_end_date %>
		   	</div>
		   	<div class="span3">
		   		<%= f.label "How Often?" %>
		   		<%= f.collection_select :recurrence_id, Recurrence.order(:id), :id, :name, include_blank: true, class: "cselect" %>
		   	</div>
		   	<div class="span3">
		   		<%= f.label "Event Price? (optional)" %>
		   		<%= f.text_field :event_price, :placeholder => "7.50", class: "input-small" %>
		   	</div>
	   	</div><br>
			
		<div class="items" id="business_hours">
			<%= f.nested_fields_for :business_hours do | builder | %>
				<%= render 'business_hour_fields', f: builder %>
			<% end %> 
			<a href="#" class="add">Add Hours</a>&nbsp(optional)
		</div>
		
		<div class="row-fluid hidden_hours_fields" id="auto_populate_hours">
			<%= f.label "Hours (Automatically Populated by Google Maps):" %>
			<br>
			<table class="hours_table">
				<tr>
					<th>Day</th>
					<th>Open</th>
					<th>Close</th>
				</tr>
				<tr>
					<td>Monday</td>
					<td id="open_monday_label"></td>
					<td id="close_monday_label"></td>
				</tr>
				<tr>
					<td>Tuesday</td>
					<td id="open_tuesday_label"></td>
					<td id="close_tuesday_label"></td>
				</tr>
				<tr>
					<td>Wednesday</td>
					<td id="open_wednesday_label"></td>
					<td id="close_wednesday_label"></td>
				</tr>
				<tr>
					<td>Thursday</td>
					<td id="open_thursday_label"></td>
					<td id="close_thursday_label"></td>
				</tr>
				<tr>
					<td>Friday</td>
					<td id="open_friday_label"></td>
					<td id="close_friday_label"></td>
				</tr>
				<tr>
					<td>Saturday</td>
					<td id="open_saturday_label"></td>
					<td id="close_saturday_label"></td>
				</tr>
				<tr>
					<td>Sunday</td>
					<td id="open_sunday_label"></td>
					<td id="close_sunday_label"></td>
				</tr>
			</table>
		</div>
		<div class="hidden">
			<input id="open_monday_" name="open_monday[]" type="text">
			<input id="close_monday_" name="close_monday[]" type="text">
			<input id="open_tuesday_" name="open_tuesday[]" type="text">
			<input id="close_tuesday_" name="close_tuesday[]" type="text">
			<input id="open_wednesday_" name="open_wednesday[]" type="text">
			<input id="close_wednesday_" name="close_wednesday[]" type="text">
			<input id="open_thursday_" name="open_thursday[]" type="text">
			<input id="close_thursday_" name="close_thursday[]" type="text">
			<input id="open_friday_" name="open_friday[]" type="text">
			<input id="close_friday_" name="close_friday[]" type="text">
			<input id="open_saturday_" name="open_saturday[]" type="text">
			<input id="close_saturday_" name="close_saturday[]" type="text">
			<input id="open_sunday_" name="open_sunday[]" type="text">
			<input id="close_sunday_" name="close_sunday[]" type="text">
		</div>

		<br>
    	<%= f.label "Address:" %><br>
		<div class="row-fluid">
			<div class="span4">
		    	<%= f.label :"Street" %>
		    	<%= f.text_field :street, :placeholder => "e.g. 601 N 59th St", class: "input-xlarge" %>
			</div>
			<div class="span3">
		    	<%= f.label :"City" %>
		    	<%= f.text_field :city, :placeholder => "e.g. Seattle", class: "input-medium" %>
		    </div>
		    <div class="span3">
		    	<%= f.label :"State" %>
		    	<%= f.select :state, options_for_select(us_states, @place.state), :include_blank => "Select One"  %>
		    </div>
		</div>
		<div class="row-fluid">
			<div class="span3">
		    	<%= f.label :"Zip Code" %>
		    	<%= f.text_field :zip_code, :placeholder => "e.g. 98103", class: "input-medium"%>
			</div>
			<div class="span3">
		    	<%= f.label "Phone Number (optional)" %>
	    		<%= f.text_field :phone_num, :placeholder => "e.g. (206) 123-456", class: "input-medium" %>
	    	</div>
	    	<div class="span3">
	    		<%= f.label "Website (optional)" %>
	    		<%= f.text_field :website, :placeholder => "e.g. http://www.example.com", class: "input-large" %>
	    	</div>
	    	<br /><br />
	    </div>

	    <%= f.submit "Save Joey Spot", class: "btn  btn-primary"%>
	<% end %>
</div>
<script>
	document.getElementById('place_category_id').addEventListener("change", function(){
		//If its an event, we don't want the autopopulated hours, its very likely the autopopulated is wrong for events
	    category = $('#place_category_id :selected').text();
	    if (category == 'Events') {
	    	removeAutopopulateHours();
	    } else {

	    }
	}, false);
</script>

app/views/places/edit.html.erb
<label class="hidden" id="editViewLabel">Edit</label>

<%= render 'form' %>

<%= link_to 'Back', @place %>

app/views/places/show.mobile.erb
<!-- Removing possible apostrophe's from the title --> 
<% str = @place.name %>
<% str = str.tr(%q{''}, '') %>
<% provide(:title, str) %>
<% if @place.photos.first != nil %>
  <% meta og: {
      title: str,
      description: @place.description,
      image: @place.photos.first.image_url.to_s
    }
  %>
<% else %>
  <% meta og: {
      title: str,
      description: @place.description,
    }
  %>
<% end %>
<div id = "show" data-role="page">
	<%= render 'layouts/header' %>
	<div data-role="content">
		<%= render 'layouts/flash_message' %>
		<ul data-role="listview" data-inset="false">
		    <li>
		    		<h2><%= @place.name %></h2>
			    	<%= content_tag "div", id: "review_value", data: {rating: @place.rating} do %>  
						<div id="star_value">
						</div>

					<% end %>
					<font size='1'>Kid-Friendly Rating (<%= pluralize(@place.reviews.count, 'Review') %>)</font><br>
			</li>
			<% if @place.votes > 0 %>
				<li>
					<small><%= pluralize @place.votes, "Joeysearcher" %>&nbsp&nbsp<%= image_tag('heart.png', id: 'like', size: '20x20') %>&nbsp this spot!</small>
				</li>
			<% end %>
			<li>
				<font size='2'><%= Category.find(@place.category_id).name %> </font>
			</li>
			<li>
				<small><%= @place.street %>, <%= @place.city %>, <%= @place.state %> <%= @place.zip_code %></small>
			</li>
		    <li><center>
			    	<%= content_tag "div", class: 'google-maps', id: "map", style: 'width: 90%; height: 200px; max-width: 400px', data: { coords: @map_coords_hash.to_json} do %>
					<% end %>
				</center>
			</li>
			<li>
				<% address = "#{@place.street}, #{@place.city}, #{@place.state} - #{@place.zip_code}" %>
        		<strong><%= link_to "Directions", "http://maps.google.com/maps?saddr=&daddr=#{address}", target: '_blank' %></strong>
			</li>
			<% unless @place.phone_num.blank? %>
				<li>
					<strong><%= number_to_phone @place.phone_num, area_code: true %></strong>
				</li>
			<% end %>
			<% unless @place.website.blank? %>
				<li>
					<strong><%= link_to "Website", @place.website, target: '_blank' %></strong>
				</li>
			<% end %>
			<% unless @place.category_id == Category.where(name: "Events")[0].id %>
		    	<li>
		    		<h4>Price: <%= intToPrice(@place.price) %></h4>
				</li>
			<% else %>
				<% unless @place.event_price.blank? %>
					<li>
		    		<h4><%= "Event Price: " + number_to_currency(@place.event_price) %></h4>
					</li>
				<% end %>
			<% end %>
		</ul>
		<div data-role="collapsibleset" data-inset="false">
			<% unless @place.description.blank? %>
			    <div data-role="collapsible" data-inset="false">
			    	<h4><%= "Description: " + @place.description %></h4>
			        	<small><%= simple_format(@place.description) %></small>
			    </div>
			<% end %>

		    <% if @place.category_id == Category.where(name: "Events")[0].id %>
		    	<div data-role="collapsible" data-inset="false">
		    		<% if @place.event_end_date.blank? %>
		    			<h4><%= "Event Dates: " + @place.event_start_date.strftime("%B %d, %Y") + " - -- " %> </h4>
		    		<% else %>
		    			<h4><%= "Event Dates: " + @place.event_start_date.strftime("%B %d, %Y") + " - " +  @place.event_end_date.strftime("%B %d, %Y") %> </h4>
		    		<% end %>
		    		<ul data-role="listview" data-inset="false">
						<% unless @place.event_start_date.blank? %>
							<li><strong>Start Date:</strong>&nbsp<%= @place.event_start_date.strftime("%B %d, %Y") %></li>
						<% end %>

						<% unless @place.event_end_date.blank? %>
							<li><strong>End Date:</strong>&nbsp<%= @place.event_end_date.strftime("%B %d, %Y") %></li>
						<% end %>
						<% unless @place.recurrence_id.blank? %>
							<li><strong>How Often?:</strong>&nbsp<%= Recurrence.find(@place.recurrence_id).name %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

		    <% @features = PlacesFeature.where(place_id: @place.id) %>
			<% unless @place.category_id == Category.where(name: "Events")[0].id ||  @features.blank? %>
			    <div data-role="collapsible" data-inset="false">
			    	<h4>
			    		<%= "Kid Features:" %>
			    		<% @features.each_with_index do |features, index| %>
					        <% feature = Feature.find(features.feature_id) %>
					 	    <% if index < @features.size - 1 %>
					 	    	<%= feature.name + ',' %>
					 	    <% else %>
					 	    	<%= feature.name %>
					 	    <% end %>
					    <% end %>
					</h4>
			    	<ul data-role="listview" data-inset="false">
						<% for features in @features %>
					        <% feature = Feature.find(features.feature_id) %>
					 	    <li><%= feature.name %></li>
					    <% end %>
			        </ul>
			    </div>
		    <% end %>
		    <div data-role="collapsible" data-inset="false">
		    	<% @ages = PlacesAgeGroup.where(place_id: @place.id).order("age_group_id ASC") %>
		    	<h4>
		    		<%= "Ages (in years):" %>
		    		<% @ages.each_with_index do | ages, index | %>
		    			<% age_group = AgeGroup.find(ages.age_group_id) %>
		    			<% if index < @ages.size - 1 %>
				 	    	<%= age_group.group_name + ',' %>
				 	    <% else %>
				 	    	<%= age_group.group_name %>
				 	    <% end %>
		    		<% end %>
		    	</h4>
		    	<ul data-role="listview" data-inset="false">
		    		<% for ages in @ages %>
			          <% age_group = AgeGroup.find(ages.age_group_id) %>
			          <li><%= age_group.group_name %>&nbsp(<%= age_group.description %>)</li>
			        <% end %>
		        </ul>
		    </div>

		    <% @businessHours = BusinessHour.where(place_id: @place.id) %>
    		<% unless @businessHours.blank? %>
			    <div data-role="collapsible" data-inset="false">
			    	<h4>Hours</h4>
		    		<ul data-role="listview" data-inset="true">
		    			<% for bh in @businessHours %>
		    				<li>
		    					<h5><%= bh.day %>:</h5>
								<% if bh.closed %>
									<b><%= "Closed" %></b>
								<% else %>
									<%= bh.open_time.to_time.strftime("%I:%M %p")  %> - <%= bh.close_time.to_time.strftime("%I:%M %p") %> 
								<% end %>
							</li>
						<% end %>
					</ul>	        
			    </div>
			<% end %>	       
		</div>

		<center>
			<div data-role="controlgroup" data-type="vertical" data-mini="false">
			    <%= link_to("Write a Review", new_place_review_path(@place.id), class: "ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-comment", "data-ajax" => "false") %>
			    <% if current_user && !current_user.voted_place_up_yet?(@place) %>
					<div id="up-<%= @place.id %>" >
					  <%= link_to "Like!", vote_place_path(@place.id, value: 1), :id => "up_vote-" + @place.id.to_s, method: "post", "data-ajax" => "false", class: "ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-heart", "data-ajax" => "false" %>
					</div>
					<div id="down-<%= @place.id %>" style="display: none;" >
					  <%= link_to "Unlike", vote_place_path(@place.id, value: 0), :id => "down_vote-" + @place.id.to_s, method: "post", "data-ajax" => "false",  class: "ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-delete" %>
					</div>
				<% else %>
					<% if current_user %>
					  <div id="down-<%= @place.id %>" >
					    <%= link_to "Unlike", vote_place_path(@place.id, value: 0), :id => "down_vote-" + @place.id.to_s, method: "post", "data-ajax" => "false",  class: "ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-delete", "data-icon" => "delete" %>
					  </div>
					  <div id="up-<%= @place.id %>" style="display: none;" >
					    <%= link_to "Like!", vote_place_path(@place.id, value: 1), :id => "up_vote-" + @place.id.to_s, method: "post", "data-ajax" => "false", class: "ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-heart", "data-ajax" => "false" %>
					  </div>
					<% end %>
				<% end %>
			    <%= link_to("View/Add Photos", place_photos_path(@place), class: "ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-camera", "data-ajax" => "false") %>
			    <%= link_to("Edit Info", edit_place_path(@place), class: "ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-edit", "data-ajax" => "false") %>
			</div>
		</center>
		<br>
		<%= will_paginate @reviews, 
		    renderer: WillPaginate::ActionView::JqueryMobilePaginateLinkRenderer,
		    previous_label: 'Prev',
		    next_label: 'Next'
		  %>
		<br>
		<div data-role="listview" data-inset="false">
			<li data-role="list-divider">
				Reviews
			</li>
			<% if @reviews.empty? %>
				<li>
					There are no reviews yet, be the first!
				</li>
			<% end %>
				<%= render @reviews %></div>
		</div>
		<%= will_paginate @reviews, 
		    renderer: WillPaginate::ActionView::JqueryMobilePaginateLinkRenderer,
		    previous_label: 'Prev',
		    next_label: 'Next'
		  %>
		<br>
		<center>
 			<%= link_to "Full Site", root_path(:mobile => 0), "data-ajax" => "false", :class => "ui-btn ui-btn-inline" %>
 		</center>
	</div>

	<%= javascript_include_tag "mobile/mobile" %>
	<%= javascript_include_tag "mobile/maps.mobile" %>
	<%= javascript_include_tag "mobile/places.mobile" %>
</div>