config/routes.rb
require 'api_constraints'

Kiddospots::Application.routes.draw do
  resources :events

  resources :android_beta_testers

  resources :event_suggestions

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
             :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :places do
        resources :photos 
        match 'photos/upload', to: 'photos#upload', via: :post
        match 'user_reviewed', to: 'reviews#user_reviewed', via: :post
        resources :reviews do
          match 'vote', to: 'reviews#vote', via: :post
        end
      end      

      match 'values/categories', to: 'values#categories', via: :get
      match 'values/features', to: 'values#features', via: :get
      match 'values/age_groups', to: 'values#age_groups', via: :get

      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        patch 'registrations' => 'registrations#update', :as => 'user_update'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
        
    end
  end

  resources :photos
  resources :reviews do
    member { post :vote }
  end

  resources :places do
      member { post :vote }
  end

  resources :places do
    resources :reviews
    resources :photos
  end
  resources :users

 devise_scope :user do 
      match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  apipie
  root  'welcome#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/auth/:provider/callback', to: 'sessions#createfb', via: 'get'

  match '/android_beta', to: 'android_beta_testers#new', via: 'get'
  

  

end

app/views/layouts/_flash_message.mobile.erb
<% if flash.any? %>
	<div data-role="collapsible" data-inset="false" data-collapsed="false">
	    <% flash.each do |key, value| %>
	      	<h4><%= key.to_s %></h4>
	      	<% if key.to_s == "error" || key.to_s == "alert" %>
	        	<font color="red"><p><%= value %></p></font>
	        <% else %>
	        	<font color="green"><p><%= value %></p></font>
	        <% end %>
	      
	    <% end %>
	</div>
	<br>
<% end %>

app/views/layouts/_header.html.erb
<header id="header" class="navbar">
	<div class="navbar-inner">
   		<div class="navbar-container">
        <div class="span2" id="logobox">
   			  <%= link_to image_tag("joey.png", alt: "Joey Search"), root_path, 'data-no-turbolink' => true %>
        </div>
        <div class="span7" id="headersearchform">
          <%= render "layouts/search_form" %>
          <ul class="nav navbar-nav ">
            <li><%= link_to "Home",  root_path, 'data-no-turbolink' => true %></li>
            <li><%= link_to "Advanced Search", places_path %></li>
            <li><%= link_to "Add Joey Spot",  new_place_path, 'data-no-turbolink' => true %></li>
            <!--[if lte IE 9]>
              <li><%= link_to "Help", help_path %></li>
            <![endif]-->
            <![if (gt IE 9) | !(IE)]>
              <li><%= link_to "Feedback", help_path %></li>
            <![endif]>  
            <li><%= link_to "About", about_path %></li>
          </ul>
        </div>
        <div class="span3">
     			<nav>
     				<% if user_signed_in? %>
     					<ul class="nav pull-right">
     						<li><%= link_to "Profile", current_user %></li>
     						<li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
     					</ul>
  				  <% else %>
  	       			<ul class="nav pull-right">
  	       				<li><%= link_to "Log In",  new_user_session_path %></li>
  	       	 			<li><%= link_to "Sign Up", new_user_registration_path %></li>
  	      			</ul>
  	      	<% end %>
     			</nav>
        </div>
   		</div>
	</div>
</header>

app/views/layouts/_header.mobile.erb
<div data-role="panel" id="panel-menu" data-position="right" data-display="overlay" data-theme="a" class="ui-panel ui-panel-position-right ui-panel-display-overlay ui-body-b ui-panel-open">
    <div class="ui-panel-inner">
    	<ul data-role="listview">
		    <li data-icon='home'><%= link_to "Home", root_path, "data-ajax" => "false" %></li>
		    <li data-icon='search'><%= link_to "Advanced Search", places_path, "data-ajax" => "false" %></li>
		    <li data-icon='location'><%= link_to "Add a Joey Spot", new_place_path, "data-ajax" => "false" %></li>
		    <li data-icon='mail'><%= link_to "Feedback", help_path %></li>
		    <li data-icon='info'><%= link_to "About", about_path %></li>
		    <% if user_signed_in? %>
		    	<li data-icon='user'><%= link_to "Profile", current_user, "data-ajax" => "false" %></li>
		    	<li data-icon='action'><%= link_to "Sign Out", destroy_user_session_path, method: "delete", "data-ajax" => "false" %></li>
		    <% else %>
		    	<li data-icon='user'><%= link_to "Log In", new_user_session_path, "data-ajax" => "false" %></li>
		    	<li data-icon='heart'><%= link_to "Sign Up", new_user_registration_path, "data-ajax" => "false" %></li>
		    <% end %>
		</ul>
		<br>

    	<a href="" data-rel="close" data-role="button" data-theme="c" data-icon="delete" data-iconpos="notext">
    	</a>
    </div>
</div>
<div data-role="panel" id="panel-search" data-position="left" data-display="overlay" data-theme="a" class="ui-panel ui-panel-position-left ui-panel-display-overlay ui-body-b ui-panel-open">
    <div class="ui-panel-inner">
		<%= form_tag places_path, method: 'get', 'data-ajax' => 'false', id: "searchForm" do %>
		  <%= text_field_tag :name, params[:name], placeholder: "Search for" %>
		  <%= text_field_tag :near, params[:near], placeholder: "Near" %>
		  <br>
		  <a href="#" id="searchCurrentLocation" data-role="button" data-inline="true" data-icon="star" >Current Location</a>
		  <%= button_tag("Search", type: "submit", class: "ui-btn ui-corner-all ui-icon-search ui-btn-icon-left") %>
		<% end %>
		<br>
    	<a href="" data-rel="close" data-role="button" data-theme="c" data-icon="delete" data-iconpos="notext">
    	</a>
    </div>
</div>
<div data-role="header">
	<a href="#panel-search" data-iconpos="notext" data-icon="search"></a>
	<center>
		<%= link_to image_tag("joey.png", alt: "Joey Search", :id => "mobile_logo"), root_path, "data-ajax" => "false" %>
	</center>
	<a href="#panel-menu" data-iconpos="notext" data-icon="bars"></a>
</div>
<script>

    $( document ).on( "click", "#searchCurrentLocation", function() {
      currentLocation();
    });

    function successFunction(position) {
        var lat = position.coords.latitude;
        var lon = position.coords.longitude;
        $('#near').val(lat + ", " + lon);
    }

    function errorFunction(error) {
          switch (error.code) {
          case error.PERMISSION_DENIED:
              alert("Joeysearch was not allowed to use your current location");
              break;

          case error.POSITION_UNAVAILABLE:
              FAIL("Joeysearch could not find your current location");
              break;

          case error.TIMEOUT:
              FAIL("Joeysearch timed out retrieving your current location");
              break;

          case error.UNKNOWN_ERROR:
              FAIL("Joeysearch encountered an unknown error while retrieving your current location");
              break;
          }
          return;
      }

      function currentLocation() {
        if (navigator.geolocation) {
	        navigator.geolocation.getCurrentPosition(successFunction, errorFunction)
	    }
      }
</script>

app/views/layouts/_search_form.html.erb
<%= form_tag places_path, method: 'get', class: "navbar-search pull-left" do %>
	<!--[if lte IE 9]>
		Search for:
		<%= text_field_tag :name, params[:name], class: "search-query span2", placeholder: "Search for" %>
		Near:
		<%= text_field_tag :near, params[:near], class: "search-query span2", placeholder: "Near" %>
	<![endif]-->
	<![if (gt IE 9) | !(IE)]>
		<%= text_field_tag :name, params[:name], class: "search-query span3", placeholder: "Search for" %>
  		<%= text_field_tag :near, params[:near], class: "search-query span3", placeholder: "Near" %>
	<![endif]>  
	<%= button_tag(type: "submit", class: "btn small btn-by circle-item") do %>
		<i class="micon-search"></i>
	<% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript">
</script>
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= metamagic %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="super-container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <% if is_mobile_device? %>
        <div>
            <br><br>
            <%= link_to "Mobile Site", root_path(:mobile => 1) %>
            <br>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.2/jquery.mobile.structure-1.4.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script>
    <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript">
    </script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>
    <%= stylesheet_link_tag "mobile/mobile" %>
    <%= csrf_meta_tags %>
    <%= metamagic %>
  </head>
  <body>
  	<%= yield %>
  </body>

</html>